# Generated by Django 5.2.7 on 2025-10-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocailMedia',
            new_name='SocialMedia',
        ),
    ]
