# Generated by Django 5.2.7 on 2025-10-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_socailmedia_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='type',
            field=models.CharField(choices=[('short_term', 'Short Term'), ('long_term', 'Long Term'), ('primary', 'Primary')], max_length=100),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='weight_management',
            field=models.CharField(blank=True, help_text='e.g., cutting, bulking, maintenance', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='competition_date',
            field=models.DateField(blank=True, help_text='Date of next competition', null=True),
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.TextField(blank=True, help_text='List any health conditions', null=True)),
                ('mobility_issues', models.TextField(blank=True, help_text='List any mobility issues', null=True)),
                ('cleared_for_training', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
