# Generated by Django 5.2.7 on 2025-10-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_goal_type_alter_nutrition_weight_management_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='sleep_habits',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
