# Generated by Django 5.2.7 on 2025-10-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_nutrition_sleep_habits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='sleep_habits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
