# Generated by Django 5.2.7 on 2025-10-26 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_nutrition_sleep_habits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='facebook',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='youtube',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('snapchat', 'Snapchat'), ('other', 'Other')], default='google.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to=settings.AUTH_USER_MODEL),
        ),
    ]
