# Generated by Django 5.2.7 on 2025-10-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_facebook_socialmedia_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='bench_est',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='current_program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='days_per_week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='deadlift_est',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='preffered_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='squat_est',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='time_lifted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='plan',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='previouscoach',
            name='coach_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recent_training_log',
            field=models.URLField(blank=True, null=True),
        ),
    ]
