# Generated by Django 5.2.7 on 2025-10-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_equipment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('TikTok', 'TikTok'), ('YouTube', 'YouTube'), ('Snapchat', 'Snapchat'), ('Other', 'Other')], max_length=100),
        ),
    ]
