# Generated by Django 5.2.7 on 2025-10-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_monthly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
